server:
  port: 8082

spring:
  application:
    name: ms-consulta

ms1:
  url: http://localhost:8080

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000

resilience4j:
  circuitbreaker:
    instances:
      ms1CircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 1
        failureRateThreshold: 50
        waitDurationInOpenState: 10s


